name: iOS Bug Report
description: "File a bug report for the iOS platform"
title: "[iOS] "
labels: ["bug", "iOS", "triage"]
assignees:
  - Chris-RH
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: markdown
    attributes:
      value: "## Please do not link to or attach project files here!"
  - type: markdown
    attributes:
      value: Instead please send a link via email to [unitysupprt@renderheads.com](mailto:unitysupport@renderheads.com) quoting this issue in your email's subject (i.e. '[iOS] Something isn't quite right \#1234') and providing a link to the issue in your message.
  - type: input
    id: unity-version
    attributes:
      label: Unity version
      description: The specific version of the Unity editor you are using.
      placeholder: "e.g. 2021.3.27f1"
    validations:
      required: true
  - type: dropdown
    id: unity-editor-platform
    attributes:
      label: Unity editor platform
      description: The platform you're using for the Unity editor.
      options:
        - Windows
        - macOS
    validations:
      required: true
  - type: dropdown
    id: avpromoviecapture-edition
    attributes:
      label: AVPro Movie Capture edition
      options:
        - Trial
        - Basic
        - Full
    validations:
      required: true
  - type: input
    id: avpromoviecapture-version
    attributes:
      label: AVPro Movie Capture Version
      description: The version of the AVPro Movie Capture plugin you are using.
      placeholder: "e.g. 5.3.0"
    validations:
      required: true
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version being used to build your Unity project.
      placeholder: "e.g. 15.2"
    validations:
      required: true
  - type: input
    id: os-versions
    attributes:
      label: Which iOS version(s) are you using?
      description: Please provide the iOS version(s) you're reporting this issue for.
      placeholder: "e.g. 17.5.0; 18.0.1"
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: Hardware
      description: Please provide details of the hardware you're reporting this issue for.
      placeholder: "e.g. iPhone 13 Pro"
    validations:
      required: true
  - type: dropdown
    id: capture-components
    attributes:
      label: Which capture component are you using?
      options:
        - Capture From Screen
        - Capture From Camera
        - Capture From Camera 360
        - Capture From Camera 360 ODS
        - Capture From Texture
        - Capture From WebCamTexture
    validations:
      required: true
  - type: dropdown
    id: capture-mode
    attributes:
      label: Capture mode
      options:
        - Realtime
        - Offline
    validations:
      required: true
  - type: dropdown
    id: output-mode
    attributes:
      label: Which output mode are you using?
      options:
        - Video file
        - Image sequence
    validations:
      required: true
  - type: dropdown
    id: video-codecs
    attributes:
      label: Video codecs
      description: Which video codec/image format are you trying to capture?
      options:
        - H264
        - HEVC
        - MJPEG
        - PNG
        - JPEG
        - HEIF
        - TIFF
    validations:
      required: true
  - type: dropdown
    id: audio-source
    attributes:
      label: Audio source
      description: Which audio source are you trying to capture?
      options:
        - None_
        - Unity
        - Microphone
        - Manual
        - Wwise
        - Unity Audio Mixer
    validations:
      required: true
  - type: dropdown
    id: audio-codecs
    attributes:
      label: Audio codecs
      description: Which audio codec are you trying to capture to? If you're not capturing audio please select 'None_'
      options:
        - None_
        - AAC
        - FLAC
        - Apple Lossless
        - Linear PCM
        - Uncompressed
    validations:
      required: true
  - type: textarea
    id: component-config
    attributes:
      label: Any other component configuration
      description: Please provide details of any other component configuration required to reproduce this issue.
    validations:
      required: false
  - type: textarea
    id: issue
    attributes:
      label: The issue
      description: Please describe the issue, how to reproduce it and what you expected the outcome to be.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please provide any relevant log output here.
      render: shell
    validations:
      required: false
